main: main.cpp
	g++ -std=c++11 main.cpp -o main

run1:main
	./main -i input.txt -encode 

run2:main
	./main -l 

run3:main
	./main -s a

run4:main
	./main -s x

run5:main
	./main -i input.txt -decode 